spring.application.name=patient-service

#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#spring.sql.init.mode=always

#as we are specifying database in dockerimage, postgre sql driver has been set up in docker container, we are providing jdbc driver through application dependencies to establish conenction to postgre sql server running in docker container specified at address specifies in my connection string whihc is port 5432. crazy batshit
#f*ck you intellij for wasting 2 days of my life on figuring out why my container couldnt set up because your ide had a bug that uses an old api protocol making me resort to listening to a russian dude who responded two months back on your forum ending up with manually reducing docker api on its engine which actually was a pretty quick and easy fix
#we can use the above settings by uncommenting when we wanna use in memory database, through docker we use postgre so h2 not needed

server.port=4000

logging.level.root=info